### ISSUE TITLE
Is this the same as https://www.bustakube.com?

### ISSUE THREAD

**Issue by mrintern** [RX-M/bust-a-kube#1]
There is another project of the same name. I'm just curious, is this repo a fork of the project at https://www.bustakube.com ? Or does it just share the same name.  I'm only asking because i'm interested in trying out both projects for personal learning.

Thanks, 

Mrintern

**Comment by RandyAbernethy** [comment]
Thanks for the issue! First time I have seen the www web site, I do not know anything about it. If anyone else here at rx-m has run across it I'll have them add a comment. You need to setup a cluster to use the manifests in this repo (per the READMEs), if you need a quick way to get a K8s cluster going you can use the script here: https://github.com/RX-M/classfiles/blob/master/k8s-setup.md

Have fun!
